FROM ghcr.io/eooce/nodejs:main

ENV NAME=Pipeops \
    NEZHA_SERVER=nz.f4i.cn \
    NEZHA_KEY=zXlotYmDKT9Y2Jo3NF \
    CFIP=www.visa.com.tw \
    ARGO_DOMAIN=pipeops.600.free.hr \
    ARGO_AUTH=eyJhIjoiZDI0NWNiZThmNGY0YjYyMGM3ZTAzODllNDRhMDg5ZTUiLCJ0IjoiOTY1NjdjZDQtY2Y4Yi00ZDk2LWFhN2YtMGI5ODc3YTdiMTY1IiwicyI6Ik1HUmlZbVE1WVRrdE5UZzBPQzAwTkdFekxXRXdNemt0TkRaaVpXSmlNVFU1WWpReiJ9
